# Introduction To Matrices_In Python Using Numpy

In [ ]:
import numpy as np
import random

In [ ]:
M = np.array([[1,2,3],[4,5,6],[7,8,9]])
M

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
M

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

* Two by two matrix

In [ ]:
T = np.random.randint(-2,4,size=(2,2))
T

array([[-1, -2],
       [ 0,  3]])

## Particular Matrices

* Identity Matix

In [ ]:
I = np.eye(3,4)
I

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

* Zeros Matrix

In [ ]:
Z = np.zeros((3,3))
Z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

* Ones matrix

In [ ]:
O = np.ones((4,3))
O

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

* Diagonal matrix

In [ ]:
D = np.diag([1,2,3])
D

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [ ]:
C = np.diag(M)
C

array([1, 5, 9])